services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    depends_on:
      - clamav
    environment:
      PGSQL_HOST: host.docker.internal
      PGSQL_PORT: 5432
      PGSQL_USERNAME: postgres
      PGSQL_PASSWORD: j7krqxf8v23j42m4bjxygwr6w*
      PGSQL_DBNAME: ecoride-14ds
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav-server
    ports:
      - "3310:3310"
